# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/car_data.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protobuf/car_data.proto\x12\x16\x63ompany.proto.formula1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8b\x02\n\x07\x43\x61rData\x12(\n\x04\x44\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03RPM\x18\x02 \x01(\x03\x12\r\n\x05Speed\x18\x03 \x01(\x03\x12\r\n\x05nGear\x18\x04 \x01(\x03\x12\x10\n\x08Throttle\x18\x05 \x01(\x03\x12\r\n\x05\x42rake\x18\x06 \x01(\x08\x12\x0b\n\x03\x44RS\x18\x07 \x01(\x03\x12\x0e\n\x06Source\x18\x08 \x01(\t\x12\'\n\x04Time\x18\t \x01(\x0b\x32\x19.google.protobuf.Duration\x12.\n\x0bSessionTime\x18\n \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0c\x44rvierNumber\x18\x0b \x01(\tB!\xaa\x02\x1e\x43ompany.Proto.Formula1.Sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.car_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\036Company.Proto.Formula1.Session'
  _globals['_CARDATA']._serialized_start=117
  _globals['_CARDATA']._serialized_end=384
# @@protoc_insertion_point(module_scope)
