# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/circute.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf/circute.proto\x12\x16\x63ompany.proto.formula1\"\xd1\x01\n\x0b\x43ircuitInfo\x12\x35\n\x07\x43orners\x18\x01 \x03(\x0b\x32$.company.proto.formula1.TrackMarkers\x12;\n\rMarshalLights\x18\x02 \x03(\x0b\x32$.company.proto.formula1.TrackMarkers\x12<\n\x0eMarshalSectors\x18\x03 \x03(\x0b\x32$.company.proto.formula1.TrackMarkers\x12\x10\n\x08Rotation\x18\x04 \x01(\x02\"e\n\x0cTrackMarkers\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\x12\x0e\n\x06Number\x18\x03 \x01(\x03\x12\x0e\n\x06Letter\x18\x04 \x01(\t\x12\r\n\x05\x41ngle\x18\x05 \x01(\x02\x12\x10\n\x08\x44istance\x18\x06 \x01(\x02\x42!\xaa\x02\x1e\x43ompany.Proto.Formula1.Circuitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.circute_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\036Company.Proto.Formula1.Circuit'
  _globals['_CIRCUITINFO']._serialized_start=51
  _globals['_CIRCUITINFO']._serialized_end=260
  _globals['_TRACKMARKERS']._serialized_start=262
  _globals['_TRACKMARKERS']._serialized_end=363
# @@protoc_insertion_point(module_scope)
