# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/race_control_messages.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$protobuf/race_control_messages.proto\x12\x16\x63ompany.proto.formula1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n\x13RaceControlMessages\x12(\n\x04Time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x43\x61tegory\x18\x02 \x01(\t\x12\x0f\n\x07Message\x18\x03 \x01(\t\x12\x0e\n\x06Status\x18\x04 \x01(\t\x12\x0c\n\x04\x46lag\x18\x05 \x01(\t\x12\r\n\x05Scope\x18\x06 \x01(\t\x12\x0e\n\x06Sector\x18\x07 \x01(\x02\x12\x14\n\x0cRacingNumber\x18\x08 \x01(\tB!\xaa\x02\x1e\x43ompany.Proto.Formula1.Sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.race_control_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\036Company.Proto.Formula1.Session'
  _globals['_RACECONTROLMESSAGES']._serialized_start=98
  _globals['_RACECONTROLMESSAGES']._serialized_end=279
# @@protoc_insertion_point(module_scope)
