# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/request.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf/request.proto\x12\x16\x63ompany.proto.formula1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n\x0eRequestSession\x12\x0c\n\x04Year\x18\x01 \x01(\x03\x12\x11\n\tGrandPrix\x18\x02 \x01(\x03\x12\x37\n\nIdentifier\x18\x03 \x01(\x0e\x32#.company.proto.formula1.Identifiers\x12\x14\n\x0cPositionData\x18\x04 \x01(\x08\x12\x0f\n\x07\x43\x61rData\x18\x05 \x01(\x08\"q\n\x15SessionStatusResponse\x12(\n\x04Time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x06Status\x18\x02 \x01(\x0e\x32\x1e.company.proto.formula1.Status*\x8f\x01\n\x0bIdentifiers\x12\x08\n\x04RACE\x10\x00\x12\x0e\n\nQUALIFYING\x10\x01\x12\n\n\x06SPRINT\x10\x02\x12\x15\n\x11SPRINT_QUALIFYING\x10\x03\x12\x13\n\x0fSPRINT_SHOOTOUT\x10\x04\x12\x0e\n\nPRACTICE_1\x10\x05\x12\x0e\n\nPRACTICE_2\x10\x06\x12\x0e\n\nPRACTICE_3\x10\x07*L\n\x06Status\x12\t\n\x05SENDT\x10\x00\x12\x0b\n\x07RECIVED\x10\x01\x12\x0b\n\x07STARTED\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\x0e\n\nSIMULATING\x10\x04\x42!\xaa\x02\x1e\x43ompany.Proto.Formula1.Requestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\036Company.Proto.Formula1.Request'
  _globals['_IDENTIFIERS']._serialized_start=347
  _globals['_IDENTIFIERS']._serialized_end=490
  _globals['_STATUS']._serialized_start=492
  _globals['_STATUS']._serialized_end=568
  _globals['_REQUESTSESSION']._serialized_start=84
  _globals['_REQUESTSESSION']._serialized_end=229
  _globals['_SESSIONSTATUSRESPONSE']._serialized_start=231
  _globals['_SESSIONSTATUSRESPONSE']._serialized_end=344
# @@protoc_insertion_point(module_scope)
