# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/session_status.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotobuf/session_status.proto\x12\x16\x63ompany.proto.formula1\x1a\x1egoogle/protobuf/duration.proto\"H\n\rSessionStatus\x12\'\n\x04Time\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x0e\n\x06Status\x18\x02 \x01(\tB!\xaa\x02\x1e\x43ompany.Proto.Formula1.Sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.session_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\036Company.Proto.Formula1.Session'
  _globals['_SESSIONSTATUS']._serialized_start=89
  _globals['_SESSIONSTATUS']._serialized_end=161
# @@protoc_insertion_point(module_scope)
